import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { Header, Footer } from '../components'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <div className="flex items-center flex-col h-[560px]">
          <div className="w-full h-full">
            <div className="absolute w-full h-full z-2 bg-slate-500 bg-opacity-30">

            </div>
            <video className="w-full h-full object-cover" autoPlay loop muted controls={false}>
              <source src="./slide-1.mp4" />
            </video>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}
